SELECT CURRENT_database();
select current_user;
select current_schema();
show search_path;
show transaction_read_only;

--Auto-commit 상태 확인

-- Chapter 06. 01 정규화 전·후 기본 구조 생성
-- 시작 상태: Chapter 06 실습 테이블이 없음
-- 완료 상태: 원시 테이블과 정규화 후 기본 테이블이 모두 비어 있는 상태로 생성됨
-- 이 단계에서는 PK와 데이터 타입만 만들고 업무 규칙은 04_add_integrity_rules.sql에서 추가합니다.
-- 생성 작업은 하나의 트랜잭션으로 묶어 중간 오류 시 부분 생성 상태를 남기지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

-- 변경 전 환경·시작 상태 확인
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '생성 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regnamespace('public') IS NULL THEN
        RAISE EXCEPTION '생성 중단: public 스키마가 존재하지 않습니다.';
    END IF;

    IF NOT has_schema_privilege(current_user, 'public', 'USAGE') THEN
        RAISE EXCEPTION
            '생성 중단: 사용자 %에게 public 스키마 USAGE 권한이 없습니다.',
            current_user;
    END IF;

    IF NOT has_schema_privilege(current_user, 'public', 'CREATE') THEN
        RAISE EXCEPTION
            '생성 중단: 사용자 %에게 public 스키마 CREATE 권한이 없습니다.',
            current_user;
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION '생성 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regclass('public.library_records_raw') IS NOT NULL
       OR to_regclass('public.members_nf') IS NOT NULL
       OR to_regclass('public.books_nf') IS NOT NULL
       OR to_regclass('public.loans_nf') IS NOT NULL THEN
        RAISE EXCEPTION
            '생성 중단: Chapter 06 실습 테이블이 이미 있습니다. 상태를 확인하거나 reset_normalization.sql을 사용하세요.';
    END IF;
END
$$;

BEGIN;

-- 정규화 전 구조: 대여 사건과 회원·도서 현재 사실이 한 행에 섞여 있음
CREATE TABLE public.library_records_raw (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR(50),
    member_email VARCHAR(100),
    book_title VARCHAR(200),
    author VARCHAR(100),
    borrowed_at DATE,
    due_at DATE,
    returned_at DATE
);

-- 정규화 후 기본 구조: 아직 업무 제약조건을 추가하지 않은 상태
CREATE TABLE public.members_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100),
    joined_at DATE
);

CREATE TABLE public.books_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    author VARCHAR(100),
    published_year INTEGER,
    isbn VARCHAR(20)
);

CREATE TABLE public.loans_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER,
    book_id INTEGER,
    borrowed_at DATE,
    due_at DATE,
    returned_at DATE
);

-- 완료 상태를 같은 트랜잭션 안에서 확인
DO $$
DECLARE
    v_raw_count bigint;
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
BEGIN
    IF to_regclass('public.library_records_raw') IS NULL
       OR to_regclass('public.members_nf') IS NULL
       OR to_regclass('public.books_nf') IS NULL
       OR to_regclass('public.loans_nf') IS NULL THEN
        RAISE EXCEPTION '생성 검증 실패: Chapter 06 테이블이 모두 생성되지 않았습니다.';
    END IF;

    SELECT COUNT(*) INTO v_raw_count FROM public.library_records_raw;
    SELECT COUNT(*) INTO v_member_count FROM public.members_nf;
    SELECT COUNT(*) INTO v_book_count FROM public.books_nf;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans_nf;

    IF v_raw_count <> 0
       OR v_member_count <> 0
       OR v_book_count <> 0
       OR v_loan_count <> 0 THEN
        RAISE EXCEPTION
            '생성 검증 실패: 새 테이블이 비어 있지 않습니다. raw=%, members=%, books=%, loans=%',
            v_raw_count, v_member_count, v_book_count, v_loan_count;
    END IF;
END
$$;

COMMIT;

SELECT
    to_regclass('public.library_records_raw') AS raw_table,
    to_regclass('public.members_nf') AS members_table,
    to_regclass('public.books_nf') AS books_table,
    to_regclass('public.loans_nf') AS loans_table;

-- Chapter 06. 02 정규화 전·후 정상 샘플 입력
-- 시작 상태: 01_normalization_schema.sql 실행 완료, 네 테이블이 모두 비어 있음
-- 완료 상태: raw 3행, members 2행, books 2행, loans 3행
-- 관계를 쉽게 확인하기 위해 명시적 실습 ID를 사용합니다.
-- 입력과 IDENTITY 조정을 하나의 트랜잭션으로 묶어 중간 오류 시 부분 입력을 남기지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

-- 변경 전 환경·빈 상태 확인
DO $$
DECLARE
    v_raw_count bigint;
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '입력 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION '입력 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regclass('public.library_records_raw') IS NULL
       OR to_regclass('public.members_nf') IS NULL
       OR to_regclass('public.books_nf') IS NULL
       OR to_regclass('public.loans_nf') IS NULL THEN
        RAISE EXCEPTION
            '입력 중단: Chapter 06 테이블이 모두 존재하지 않습니다. 01_normalization_schema.sql을 먼저 실행하세요.';
    END IF;

    SELECT COUNT(*) INTO v_raw_count FROM public.library_records_raw;
    SELECT COUNT(*) INTO v_member_count FROM public.members_nf;
    SELECT COUNT(*) INTO v_book_count FROM public.books_nf;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans_nf;

    IF v_raw_count <> 0
       OR v_member_count <> 0
       OR v_book_count <> 0
       OR v_loan_count <> 0 THEN
        RAISE EXCEPTION
            '입력 중단: 빈 테이블이 아닙니다. raw=%, members=%, books=%, loans=%',
            v_raw_count, v_member_count, v_book_count, v_loan_count;
    END IF;
END
$$;

BEGIN;

INSERT INTO public.library_records_raw (
    loan_id,
    member_name,
    member_email,
    book_title,
    author,
    borrowed_at,
    due_at,
    returned_at
)
VALUES
    (1001, '김민지', 'minji@example.com', '데이터베이스 입문', '문길래', DATE '2026-04-01', DATE '2026-04-15', DATE '2026-04-02'),
    (1002, '김민지', 'minji@example.com', 'SQL 기초', '홍길동', DATE '2026-04-02', DATE '2026-04-16', NULL),
    (1003, '이준호', 'junho@example.com', '데이터베이스 입문', '문길래', DATE '2026-04-03', DATE '2026-04-17', NULL);

INSERT INTO public.members_nf (id, name, email, joined_at)
VALUES
    (101, '김민지', 'minji@example.com', DATE '2026-03-01'),
    (102, '이준호', 'junho@example.com', DATE '2026-03-05');

INSERT INTO public.books_nf (id, title, author, published_year, isbn)
VALUES
    (201, '데이터베이스 입문', '문길래', 2026, 'ISBN-001'),
    (202, 'SQL 기초', '홍길동', 2025, 'ISBN-002');

INSERT INTO public.loans_nf (
    id,
    member_id,
    book_id,
    borrowed_at,
    due_at,
    returned_at
)
VALUES
    (1001, 101, 201, DATE '2026-04-01', DATE '2026-04-15', DATE '2026-04-02'),
    (1002, 101, 202, DATE '2026-04-02', DATE '2026-04-16', NULL),
    (1003, 102, 201, DATE '2026-04-03', DATE '2026-04-17', NULL);

-- 명시적 ID 뒤의 자동 생성값이 샘플 ID와 충돌하지 않도록 조정합니다.
ALTER TABLE public.library_records_raw
    ALTER COLUMN loan_id RESTART WITH 1004;

ALTER TABLE public.members_nf
    ALTER COLUMN id RESTART WITH 103;

ALTER TABLE public.books_nf
    ALTER COLUMN id RESTART WITH 203;

ALTER TABLE public.loans_nf
    ALTER COLUMN id RESTART WITH 1004;

-- 완료 상태를 커밋 전에 확인
DO $$
DECLARE
    v_raw_count bigint;
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
    v_open_count bigint;
    v_member_101_count bigint;
    v_book_201_count bigint;
BEGIN
    SELECT COUNT(*) INTO v_raw_count FROM public.library_records_raw;
    SELECT COUNT(*) INTO v_member_count FROM public.members_nf;
    SELECT COUNT(*) INTO v_book_count FROM public.books_nf;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans_nf;
    SELECT COUNT(*) INTO v_open_count FROM public.loans_nf WHERE returned_at IS NULL;
    SELECT COUNT(*) INTO v_member_101_count FROM public.loans_nf WHERE member_id = 101;
    SELECT COUNT(*) INTO v_book_201_count FROM public.loans_nf WHERE book_id = 201;

    IF v_raw_count <> 3
       OR v_member_count <> 2
       OR v_book_count <> 2
       OR v_loan_count <> 3
       OR v_open_count <> 2
       OR v_member_101_count <> 2
       OR v_book_201_count <> 2 THEN
        RAISE EXCEPTION
            '입력 검증 실패: raw=%, members=%, books=%, loans=%, open=%, member101=%, book201=%',
            v_raw_count,
            v_member_count,
            v_book_count,
            v_loan_count,
            v_open_count,
            v_member_101_count,
            v_book_201_count;
    END IF;
END
$$;

COMMIT;

SELECT COUNT(*) AS raw_count FROM public.library_records_raw;
SELECT COUNT(*) AS member_count FROM public.members_nf;
SELECT COUNT(*) AS book_count FROM public.books_nf;
SELECT COUNT(*) AS loan_count FROM public.loans_nf;


-- Chapter 06. 03 정규화 전·후 비교와 기본 검증
-- 시작 상태: 02_normalization_seed.sql 실행 완료
-- 완료 상태: 데이터 변경 없이 반복·행 수·관계·시간 순서를 확인
-- 이 파일은 데이터를 변경하지 않으므로 반복 실행할 수 있습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

DO $$
DECLARE
    v_raw_count bigint;
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
    v_open_count bigint;
    v_member_101_count bigint;
    v_book_201_count bigint;
    v_orphan_member_count bigint;
    v_orphan_book_count bigint;
    v_invalid_date_count bigint;
    v_book_201_invalid_order bigint;
    v_active_duplicate_count bigint;
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '비교 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('public.library_records_raw') IS NULL
       OR to_regclass('public.members_nf') IS NULL
       OR to_regclass('public.books_nf') IS NULL
       OR to_regclass('public.loans_nf') IS NULL THEN
        RAISE EXCEPTION
            '비교 중단: Chapter 06 테이블이 모두 존재하지 않습니다.';
    END IF;

    SELECT COUNT(*) INTO v_raw_count FROM public.library_records_raw;
    SELECT COUNT(*) INTO v_member_count FROM public.members_nf;
    SELECT COUNT(*) INTO v_book_count FROM public.books_nf;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans_nf;
    SELECT COUNT(*) INTO v_open_count FROM public.loans_nf WHERE returned_at IS NULL;
    SELECT COUNT(*) INTO v_member_101_count FROM public.loans_nf WHERE member_id = 101;
    SELECT COUNT(*) INTO v_book_201_count FROM public.loans_nf WHERE book_id = 201;

    SELECT COUNT(*) INTO v_orphan_member_count
    FROM public.loans_nf AS l
    LEFT JOIN public.members_nf AS m
        ON l.member_id = m.id
    WHERE m.id IS NULL;

    SELECT COUNT(*) INTO v_orphan_book_count
    FROM public.loans_nf AS l
    LEFT JOIN public.books_nf AS b
        ON l.book_id = b.id
    WHERE b.id IS NULL;

    SELECT COUNT(*) INTO v_invalid_date_count
    FROM public.loans_nf
    WHERE due_at < borrowed_at
       OR (returned_at IS NOT NULL AND returned_at < borrowed_at);

    SELECT COUNT(*) INTO v_book_201_invalid_order
    FROM public.loans_nf AS earlier
    JOIN public.loans_nf AS later
        ON earlier.book_id = later.book_id
       AND earlier.borrowed_at < later.borrowed_at
    WHERE earlier.book_id = 201
      AND earlier.returned_at IS NOT NULL
      AND earlier.returned_at >= later.borrowed_at;

    SELECT COUNT(*) INTO v_active_duplicate_count
    FROM (
        SELECT book_id
        FROM public.loans_nf
        WHERE returned_at IS NULL
        GROUP BY book_id
        HAVING COUNT(*) > 1
    ) AS duplicated_active_books;

    IF v_raw_count <> 3
       OR v_member_count <> 2
       OR v_book_count <> 2
       OR v_loan_count <> 3
       OR v_open_count <> 2
       OR v_member_101_count <> 2
       OR v_book_201_count <> 2
       OR v_orphan_member_count <> 0
       OR v_orphan_book_count <> 0
       OR v_invalid_date_count <> 0
       OR v_book_201_invalid_order <> 0
       OR v_active_duplicate_count <> 0 THEN
        RAISE EXCEPTION
            '비교 검증 실패: raw=%, members=%, books=%, loans=%, open=%, member101=%, book201=%, orphan_member=%, orphan_book=%, invalid_date=%, book201_order=%, active_duplicate=%',
            v_raw_count,
            v_member_count,
            v_book_count,
            v_loan_count,
            v_open_count,
            v_member_101_count,
            v_book_201_count,
            v_orphan_member_count,
            v_orphan_book_count,
            v_invalid_date_count,
            v_book_201_invalid_order,
            v_active_duplicate_count;
    END IF;

    RAISE NOTICE 'Chapter 06 normalization comparison passed';
END
$$;

-- 정규화 전 원시 데이터
SELECT *
FROM public.library_records_raw
ORDER BY loan_id;

-- 같은 회원 사실의 반복
SELECT
    member_name,
    member_email,
    COUNT(*) AS repeated_rows
FROM public.library_records_raw
GROUP BY member_name, member_email
ORDER BY repeated_rows DESC, member_name;

-- 같은 도서 사실의 반복
SELECT
    book_title,
    author,
    COUNT(*) AS repeated_rows
FROM public.library_records_raw
GROUP BY book_title, author
ORDER BY repeated_rows DESC, book_title;

-- 정규화 후 각 사실의 주인 테이블
SELECT * FROM public.members_nf ORDER BY id;
SELECT * FROM public.books_nf ORDER BY id;
SELECT * FROM public.loans_nf ORDER BY id;

-- 정규화된 관계가 원래 업무 결과를 만들 수 있는지 확인
-- JOIN 상세 문법은 Chapter 08에서 다룹니다.
SELECT
    l.id AS loan_id,
    m.name AS member_name,
    m.email AS member_email,
    b.title AS book_title,
    b.author,
    l.borrowed_at,
    l.due_at,
    l.returned_at
FROM public.loans_nf AS l
JOIN public.members_nf AS m
    ON l.member_id = m.id
JOIN public.books_nf AS b
    ON l.book_id = b.id
ORDER BY l.id;

-- 회원 101과 도서 201의 반복 이력
SELECT *
FROM public.loans_nf
WHERE member_id = 101
ORDER BY borrowed_at, id;

SELECT *
FROM public.loans_nf
WHERE book_id = 201
ORDER BY borrowed_at, id;

-- 미반납 대여
SELECT *
FROM public.loans_nf
WHERE returned_at IS NULL
ORDER BY due_at, id;


select * from library_records_raw lrr ;
select * from members_nf mn ;
select * from books_nf bn ;
select * from loans_nf t
--원래는 llr에 있던 속성이 t에도 있어야 한다. 하지만 정규화되어 members_id나 book_id로 바뀌었다. 
where t.returned_at is null;

select count(*) from loans_nf t
where t.member_id = 101;

select count(*) from loans_nf t
where t.book_id  = 201;

select * from loans_nf t
where t.member_id = 101 and t.book_id  = 201;

-- loan_nf 테이블에서 도서 테이블에 등록되지 않은 도서의 대출 건수를 구하시오
-- loan_nf.book_id 중 books_nf 테이블에 중복되지 않는 id에 포함되지 않는 book_id가 있는가
select id from books_nf bn ;
--201, 202
select t.id ,t.member_id  from loans_nf t 
where t.book_id not in (select id from books_nf bn) ;

select t.id ,bn.title from loans_nf t 
inner join books_nf bn 
on t.book_id = bn.id
--이게 join의 기본 쿼리
where t.book_id not in (201,202);


SELECT email, COUNT(*)
FROM public.members_nf
GROUP BY email
HAVING COUNT(*) > 1;





